# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08pp.proto\"m\n\x0f\x43onv2dParameter\x12\x13\n\x0bin_channels\x18\x01 \x01(\r\x12\x14\n\x0cout_channels\x18\x02 \x01(\r\x12\x0e\n\x06kernel\x18\x03 \x03(\r\x12\x0e\n\x06stride\x18\x04 \x03(\r\x12\x0f\n\x07padding\x18\x05 \x03(\r\"W\n\x0fResNetParameter\x12\x13\n\x06layers\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tfreeze_at\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\t\n\x07_layersB\x0c\n\n_freeze_at\"\xe2\x01\n\x0fModuleParameter\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04type\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x0e\n\x06\x62ottom\x18\x03 \x03(\t\x12\x0b\n\x03top\x18\x04 \x03(\t\x12+\n\x0c\x63onv2d_param\x18\x64 \x01(\x0b\x32\x10.Conv2dParameterH\x02\x88\x01\x01\x12+\n\x0cresnet_param\x18\x65 \x01(\x0b\x32\x10.ResNetParameterH\x03\x88\x01\x01\x42\x07\n\x05_nameB\x07\n\x05_typeB\x0f\n\r_conv2d_paramB\x0f\n\r_resnet_param\"N\n\x0eModelParameter\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12 \n\x06module\x18\x64 \x03(\x0b\x32\x10.ModuleParameterB\x07\n\x05_nameb\x06proto3'
)




_CONV2DPARAMETER = _descriptor.Descriptor(
  name='Conv2dParameter',
  full_name='Conv2dParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_channels', full_name='Conv2dParameter.in_channels', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='out_channels', full_name='Conv2dParameter.out_channels', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kernel', full_name='Conv2dParameter.kernel', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stride', full_name='Conv2dParameter.stride', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='padding', full_name='Conv2dParameter.padding', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=121,
)


_RESNETPARAMETER = _descriptor.Descriptor(
  name='ResNetParameter',
  full_name='ResNetParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layers', full_name='ResNetParameter.layers', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freeze_at', full_name='ResNetParameter.freeze_at', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_layers', full_name='ResNetParameter._layers',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_freeze_at', full_name='ResNetParameter._freeze_at',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=123,
  serialized_end=210,
)


_MODULEPARAMETER = _descriptor.Descriptor(
  name='ModuleParameter',
  full_name='ModuleParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ModuleParameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='ModuleParameter.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='ModuleParameter.bottom', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top', full_name='ModuleParameter.top', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conv2d_param', full_name='ModuleParameter.conv2d_param', index=4,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resnet_param', full_name='ModuleParameter.resnet_param', index=5,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='ModuleParameter._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_type', full_name='ModuleParameter._type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_conv2d_param', full_name='ModuleParameter._conv2d_param',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_resnet_param', full_name='ModuleParameter._resnet_param',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=213,
  serialized_end=439,
)


_MODELPARAMETER = _descriptor.Descriptor(
  name='ModelParameter',
  full_name='ModelParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ModelParameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='module', full_name='ModelParameter.module', index=1,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='ModelParameter._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=441,
  serialized_end=519,
)

_RESNETPARAMETER.oneofs_by_name['_layers'].fields.append(
  _RESNETPARAMETER.fields_by_name['layers'])
_RESNETPARAMETER.fields_by_name['layers'].containing_oneof = _RESNETPARAMETER.oneofs_by_name['_layers']
_RESNETPARAMETER.oneofs_by_name['_freeze_at'].fields.append(
  _RESNETPARAMETER.fields_by_name['freeze_at'])
_RESNETPARAMETER.fields_by_name['freeze_at'].containing_oneof = _RESNETPARAMETER.oneofs_by_name['_freeze_at']
_MODULEPARAMETER.fields_by_name['conv2d_param'].message_type = _CONV2DPARAMETER
_MODULEPARAMETER.fields_by_name['resnet_param'].message_type = _RESNETPARAMETER
_MODULEPARAMETER.oneofs_by_name['_name'].fields.append(
  _MODULEPARAMETER.fields_by_name['name'])
_MODULEPARAMETER.fields_by_name['name'].containing_oneof = _MODULEPARAMETER.oneofs_by_name['_name']
_MODULEPARAMETER.oneofs_by_name['_type'].fields.append(
  _MODULEPARAMETER.fields_by_name['type'])
_MODULEPARAMETER.fields_by_name['type'].containing_oneof = _MODULEPARAMETER.oneofs_by_name['_type']
_MODULEPARAMETER.oneofs_by_name['_conv2d_param'].fields.append(
  _MODULEPARAMETER.fields_by_name['conv2d_param'])
_MODULEPARAMETER.fields_by_name['conv2d_param'].containing_oneof = _MODULEPARAMETER.oneofs_by_name['_conv2d_param']
_MODULEPARAMETER.oneofs_by_name['_resnet_param'].fields.append(
  _MODULEPARAMETER.fields_by_name['resnet_param'])
_MODULEPARAMETER.fields_by_name['resnet_param'].containing_oneof = _MODULEPARAMETER.oneofs_by_name['_resnet_param']
_MODELPARAMETER.fields_by_name['module'].message_type = _MODULEPARAMETER
_MODELPARAMETER.oneofs_by_name['_name'].fields.append(
  _MODELPARAMETER.fields_by_name['name'])
_MODELPARAMETER.fields_by_name['name'].containing_oneof = _MODELPARAMETER.oneofs_by_name['_name']
DESCRIPTOR.message_types_by_name['Conv2dParameter'] = _CONV2DPARAMETER
DESCRIPTOR.message_types_by_name['ResNetParameter'] = _RESNETPARAMETER
DESCRIPTOR.message_types_by_name['ModuleParameter'] = _MODULEPARAMETER
DESCRIPTOR.message_types_by_name['ModelParameter'] = _MODELPARAMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Conv2dParameter = _reflection.GeneratedProtocolMessageType('Conv2dParameter', (_message.Message,), {
  'DESCRIPTOR' : _CONV2DPARAMETER,
  '__module__' : 'pp_pb2'
  # @@protoc_insertion_point(class_scope:Conv2dParameter)
  })
_sym_db.RegisterMessage(Conv2dParameter)

ResNetParameter = _reflection.GeneratedProtocolMessageType('ResNetParameter', (_message.Message,), {
  'DESCRIPTOR' : _RESNETPARAMETER,
  '__module__' : 'pp_pb2'
  # @@protoc_insertion_point(class_scope:ResNetParameter)
  })
_sym_db.RegisterMessage(ResNetParameter)

ModuleParameter = _reflection.GeneratedProtocolMessageType('ModuleParameter', (_message.Message,), {
  'DESCRIPTOR' : _MODULEPARAMETER,
  '__module__' : 'pp_pb2'
  # @@protoc_insertion_point(class_scope:ModuleParameter)
  })
_sym_db.RegisterMessage(ModuleParameter)

ModelParameter = _reflection.GeneratedProtocolMessageType('ModelParameter', (_message.Message,), {
  'DESCRIPTOR' : _MODELPARAMETER,
  '__module__' : 'pp_pb2'
  # @@protoc_insertion_point(class_scope:ModelParameter)
  })
_sym_db.RegisterMessage(ModelParameter)


# @@protoc_insertion_point(module_scope)
